### ISSUE TITLE
Token error during cloning

### ISSUE THREAD

**Issue by Dilshat** [subutai-io/peer-os#2489]
Sometimes the following error appears during container cloning:
```
2018-06-08 05:39:13,996 | ERROR | pool-98-thread-1 | ContainerTokenDataService        | 157 - io.subutai.core.registration.impl - 7.0.2 | java.lang.reflect.UndeclaredThrowableException
java.lang.reflect.UndeclaredThrowableException
	at com.sun.proxy.$Proxy26.flush(Unknown Source)[71:org.apache.openjpa:2.3.0]
	at io.subutai.core.registration.impl.dao.ContainerTokenDataService.persist(ContainerTokenDataService.java:92)[157:io.subutai.core.registration.impl:7.0.2]
	at io.subutai.core.registration.impl.HostRegistrationManagerImpl.generateContainerTTLToken(HostRegistrationManagerImpl.java:343)[157:io.subutai.core.registration.impl:7.0.2]
	at Proxydbdab9b2_62be_436d_9dbe_694698214a0e.generateContainerTTLToken(Unknown Source)[:]
	at Proxydbdab9b2_62be_436d_9dbe_694698214a0e.generateContainerTTLToken(Unknown Source)[:]
	at io.subutai.core.localpeer.impl.entity.ResourceHostEntity.cloneContainer(ResourceHostEntity.java:1027)[201:io.subutai.core.localpeer.impl:7.0.2]
	at io.subutai.common.environment.CloneContainerTask.call(CloneContainerTask.java:104)[92:io.subutai.common:7.0.2]
	at io.subutai.common.environment.CloneContainerTask.call(CloneContainerTask.java:26)[92:io.subutai.common:7.0.2]
	at io.subutai.common.util.HostUtil$HostTaskCommand.call(HostUtil.java:486)[92:io.subutai.common:7.0.2]
	at io.subutai.common.util.HostUtil$HostTaskCommand.call(HostUtil.java:468)[92:io.subutai.common:7.0.2]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)[:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)[:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)[:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_171]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_171]
	at org.apache.aries.jpa.container.impl.EntityManagerProxyFactory$EMHandler.invoke(EntityManagerProxyFactory.java:31)[259:org.apache.aries.jpa.container:1.0.2]
	... 14 more
Caused by: <openjpa-2.3.0-r422266:1540826 fatal store error> org.apache.openjpa.persistence.EntityNotFoundException: The transaction has been rolled back.  See the nested exceptions for details on the errors that occurred.
FailedObject: io.subutai.core.registration.impl.entity.ContainerTokenImpl@56a04cf6
	at org.apache.openjpa.kernel.BrokerImpl.newFlushException(BrokerImpl.java:2370)
	at org.apache.openjpa.kernel.BrokerImpl.flush(BrokerImpl.java:2207)
	at org.apache.openjpa.kernel.BrokerImpl.flushSafe(BrokerImpl.java:2105)
	at org.apache.openjpa.kernel.BrokerImpl.flush(BrokerImpl.java:1876)
	at org.apache.openjpa.kernel.DelegatingBroker.flush(DelegatingBroker.java:1045)
	at org.apache.openjpa.persistence.EntityManagerImpl.flush(EntityManagerImpl.java:663)
	... 19 more
Caused by: <openjpa-2.3.0-r422266:1540826 nonfatal store error> org.apache.openjpa.persistence.EntityNotFoundException: The instance of type "class io.subutai.core.registration.impl.entity.ContainerTokenImpl" with oid "4f2162eb-7bdd-4627-8dcd-4b2a2f98c361" no longer exists in the data store.  This may mean that you deleted the instance in a separate transaction, but this context still has a cached version.
FailedObject: io.subutai.core.registration.impl.entity.ContainerTokenImpl@56a04cf6
	at org.apache.openjpa.kernel.StateManagerImpl.loadFields(StateManagerImpl.java:3109)
	at org.apache.openjpa.kernel.StateManagerImpl.loadField(StateManagerImpl.java:3188)
	at org.apache.openjpa.kernel.StateManagerImpl.fetchStringField(StateManagerImpl.java:2474)
	at org.apache.openjpa.kernel.StateManagerImpl.fetchString(StateManagerImpl.java:2464)
	at org.apache.openjpa.jdbc.meta.strats.StringFieldStrategy.insert(StringFieldStrategy.java:105)
	at org.apache.openjpa.jdbc.meta.FieldMapping.insert(FieldMapping.java:623)
	at org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.insert(AbstractUpdateManager.java:238)
	at org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.populateRowManager(AbstractUpdateManager.java:165)
	at org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.flush(AbstractUpdateManager.java:96)
	at org.apache.openjpa.jdbc.kernel.AbstractUpdateManager.flush(AbstractUpdateManager.java:77)
	at org.apache.openjpa.jdbc.kernel.JDBCStoreManager.flush(JDBCStoreManager.java:732)
	at org.apache.openjpa.kernel.DelegatingStoreManager.flush(DelegatingStoreManager.java:131)
	... 24 more
```

which results in the following:

```
2018-06-08 05:39:14,894 | ERROR | qtp640469738-179 | RegistrationRestServiceImpl      | 158 - io.subutai.core.registration.rest - 7.0.2 | Error verifying container token
io.subutai.core.registration.api.exception.HostRegistrationException: Couldn't verify container token
	at io.subutai.core.registration.impl.HostRegistrationManagerImpl.verifyToken(HostRegistrationManagerImpl.java:367)
	at Proxydbdab9b2_62be_436d_9dbe_694698214a0e.verifyToken(Unknown Source)
	at Proxydbdab9b2_62be_436d_9dbe_694698214a0e.verifyToken(Unknown Source)
	at Proxy6b7a171d_441e_4cbb_93d1_8db546f3360e.verifyToken(Unknown Source)
	at io.subutai.core.registration.rest.RegistrationRestServiceImpl.verifyContainerToken(RegistrationRestServiceImpl.java:189)[158:io.subutai.core.registration.rest:7.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_171]
	at org.apache.aries.proxy.impl.ProxyHandler$1.invoke(ProxyHandler.java:54)
	at org.apache.aries.proxy.impl.ProxyHandler.invoke(ProxyHandler.java:119)
	at io.subutai.core.registration.rest.$RegistrationRestServiceImpl56701579.verifyContainerToken(Unknown Source)[158:io.subutai.core.registration.rest:7.0.2]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)[:1.8.0_171]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)[:1.8.0_171]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)[:1.8.0_171]
	at java.lang.reflect.Method.invoke(Method.java:498)[:1.8.0_171]
	at org.apache.cxf.service.invoker.AbstractInvoker.performInvocation(AbstractInvoker.java:181)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.service.invoker.AbstractInvoker.invoke(AbstractInvoker.java:97)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:200)[107:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.jaxrs.JAXRSInvoker.invoke(JAXRSInvoker.java:99)[107:org.apache.cxf.cxf-rt-frontend-jaxrs:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor$1.run(ServiceInvokerInterceptor.java:59)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.interceptor.ServiceInvokerInterceptor.handleMessage(ServiceInvokerInterceptor.java:96)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[108:org.apache.cxf.cxf-core:3.1.0]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:68)[145:io.subutai.core.channel.impl:7.0.2]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor$1.run(AccessControlInterceptor.java:62)[145:io.subutai.core.channel.impl:7.0.2]
	at java.security.AccessController.doPrivileged(Native Method)[:1.8.0_171]
	at javax.security.auth.Subject.doAs(Subject.java:360)[:1.8.0_171]
	at io.subutai.core.channel.impl.interceptor.AccessControlInterceptor.handleMessage(AccessControlInterceptor.java:61)[145:io.subutai.core.channel.impl:7.0.2]
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:307)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.ChainInitiationObserver.onMessage(ChainInitiationObserver.java:121)[108:org.apache.cxf.cxf-core:3.1.0]
	at org.apache.cxf.transport.http.AbstractHTTPDestination.invoke(AbstractHTTPDestination.java:251)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invokeDestination(ServletController.java:234)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:208)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.ServletController.invoke(ServletController.java:160)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.CXFNonSpringServlet.invoke(CXFNonSpringServlet.java:171)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.handleRequest(AbstractHTTPServlet.java:293)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.doPost(AbstractHTTPServlet.java:212)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)[40:org.apache.geronimo.specs.geronimo-servlet_3.0_spec:1.0.0]
	at org.apache.cxf.transport.servlet.AbstractHTTPServlet.service(AbstractHTTPServlet.java:268)[113:org.apache.cxf.cxf-rt-transports-http:3.1.0]
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:503)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceServletHandler.doHandle(HttpServiceServletHandler.java:69)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.HttpServiceContext.doHandle(HttpServiceContext.java:240)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.ops4j.pax.web.service.jetty.internal.JettyServerHandlerCollection.handle(JettyServerHandlerCollection.java:75)[54:org.ops4j.pax.web.pax-web-jetty:3.2.6]
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.Server.handle(Server.java:370)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:957)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SslConnection.handle(SslConnection.java:196)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)[45:org.eclipse.jetty.aggregate.jetty-all-server:8.1.17.v20150415]
	at java.lang.Thread.run(Thread.java:748)[:1.8.0_171]
```

**Comment by Dilshat** [comment]
Note: tokens can be stored in memory not in DB

**Comment by lbthomsen** [comment]
FYI - this happened on a freshly installed peer - first time deploying a blueprint.  Repeating exactly the same worked.

**Comment by AlinaPenkina** [comment]
fixed.
